Changed manpage name, finished installer script

diff --git a/install b/install
--- a/install
+++ b/install
@@ -30,8 +30,8 @@ readonly OK="\e[7;32m OK \e[0m"
 readonly INFO="\e[7;36mINFO\e[0m"
 readonly WARN="\e[7;33mWARN\e[0m"
 readonly FAIL="\e[7;31mFAIL\e[0m"
-# Default installation directory
-installdir="/opt/jmaintenance"
+# Installation directory
+INSTALLDIR="/opt/jmaintenance"
 
 ## Preparation ##
 
@@ -63,4 +63,60 @@ VERSION="$(cat src/config.bash | grep VERSION= | awk -F = '{print $2}' | rev | c
     --yesno "This installer will set up jmaintenance, a system recovery program." 0 0 \
     && exit 0
 
-## Begin installation ##
+## Installation ##
+
+# Make installation directory under /opt
+if mkdir "$INSTALLDIR";
+then
+    printf "$OK Created installation directory: $INSTALLDIR\n"
+else
+    printf "$FAIL Failed to create installation directory: $INSTALLDIR\n"
+    exit 1
+fi
+
+# Copy files
+if cp src/*.bash "$INSTALLDIR";
+then
+    printf "$OK copied files to target directory\n"
+else
+    printf "$FAIL failed to copy files to target directory, abort!\n"
+fi
+
+# Set up symlink
+if ln -s "$INSTALLDIR/main.bash" /usr/local/sbin/jmaintenance;
+then
+    printf "$OK set up symlink under /usr/local/sbin\n"
+else
+    printf "$FAIL failed to set up symlink under /usr/local/sbin\n"
+    exit 1
+fi
+
+# Install documentation
+printf "$INFO Compressing manpage..."
+if gzip doc/jmaintenance.8;
+then
+    printf "$OK Compressed manpage\n"
+else
+    printf "$FAIL Failed to compress manpage, abort!\n"
+    exit 1
+fi
+
+mandir="/usr/local/share/man/man8/"
+if mkdir "$mandir";
+then
+    printf "$OK Created manual directory\n"
+else
+    printf "$FAIL Failed to create manual directory, abort!\n"
+fi
+
+if cp doc/jmaintenance.8.gz "$mandir"
+then
+    printf "$OK Installed manual page\n"
+else
+    printf "$FAIL Failed to install manual page, abort!"
+fi
+
+# Give final hint
+whiptail \
+    --backtitle "jmaintenance $VERSION installer" \
+    --msgbox "Installation finished. Now you can run jmaintenance from single user mode." 0 0
